# Generated by Django 5.0.4 on 2024-04-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('capacidad', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
